// Generated automatically by nearley, version 2.16.0
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "main", "symbols": ["StructureOne"]},
    {"name": "main", "symbols": ["StructureTwo"]},
    {"name": "StructureOne$string$1", "symbols": [{"literal":"\n"}, {"literal":"\n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "StructureOne$string$2", "symbols": [{"literal":"\n"}, {"literal":"#"}, {"literal":"J"}, {"literal":"A"}, {"literal":"P"}, {"literal":"A"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "StructureOne", "symbols": ["Title", "StructureOne$string$1", "ADJNOUN", {"literal":"\n"}, "ADJNOUN", {"literal":"\n"}, "ADJNOUN", "StructureOne$string$2"]},
    {"name": "StructureTwo$string$1", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"h"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}, {"literal":"d"}, {"literal":" "}, {"literal":"b"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "StructureTwo$string$2", "symbols": [{"literal":"\n"}, {"literal":"\n"}, {"literal":"S"}, {"literal":"o"}, {"literal":" "}, {"literal":"s"}, {"literal":"h"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}, {"literal":"d"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "StructureTwo$string$3", "symbols": [{"literal":" "}, {"literal":"\n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "StructureTwo", "symbols": [{"literal":"A"}, "SimpleItem", "StructureTwo$string$1", "TypeTwo", "StructureTwo$string$2", "ADJNOUNa", {"literal":"\n"}, "ADJNOUNb", {"literal":"\n"}, "ADJNOUNb", "StructureTwo$string$3", "HASHTAG"]},
    {"name": "Title$string$1", "symbols": [{"literal":" "}, {"literal":"T"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Title", "symbols": ["TitleDescriptor", "Title$string$1"]},
    {"name": "Title$string$2", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"s"}, {"literal":" "}, {"literal":"T"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}, {"literal":" "}, {"literal":"A"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Title", "symbols": ["Title$string$2", "TitleDescriptor"]},
    {"name": "TitleDescriptor$string$1", "symbols": [{"literal":"S"}, {"literal":"h"}, {"literal":"a"}, {"literal":"m"}, {"literal":"e"}, {"literal":"f"}, {"literal":"u"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TitleDescriptor", "symbols": ["TitleDescriptor$string$1"]},
    {"name": "TitleDescriptor$string$2", "symbols": [{"literal":"D"}, {"literal":"e"}, {"literal":"l"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":"f"}, {"literal":"u"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TitleDescriptor", "symbols": ["TitleDescriptor$string$2"]},
    {"name": "TitleDescriptor$string$3", "symbols": [{"literal":"P"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"a"}, {"literal":"b"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TitleDescriptor", "symbols": ["TitleDescriptor$string$3"]},
    {"name": "TitleDescriptor$string$4", "symbols": [{"literal":"D"}, {"literal":"i"}, {"literal":"s"}, {"literal":"a"}, {"literal":"p"}, {"literal":"p"}, {"literal":"o"}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TitleDescriptor", "symbols": ["TitleDescriptor$string$4"]},
    {"name": "TitleDescriptor$string$5", "symbols": [{"literal":"T"}, {"literal":"i"}, {"literal":"m"}, {"literal":"e"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TitleDescriptor", "symbols": ["TitleDescriptor$string$5"]},
    {"name": "TitleDescriptor$string$6", "symbols": [{"literal":"W"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TitleDescriptor", "symbols": ["TitleDescriptor$string$6"]},
    {"name": "TitleDescriptor$string$7", "symbols": [{"literal":"W"}, {"literal":"o"}, {"literal":"e"}, {"literal":"f"}, {"literal":"u"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TitleDescriptor", "symbols": ["TitleDescriptor$string$7"]},
    {"name": "TitleDescriptor$string$8", "symbols": [{"literal":"A"}, {"literal":"m"}, {"literal":"u"}, {"literal":"s"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TitleDescriptor", "symbols": ["TitleDescriptor$string$8"]},
    {"name": "TitleDescriptor$string$9", "symbols": [{"literal":"T"}, {"literal":"o"}, {"literal":"u"}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TitleDescriptor", "symbols": ["TitleDescriptor$string$9"]},
    {"name": "TitleDescriptor$string$10", "symbols": [{"literal":"M"}, {"literal":"e"}, {"literal":"m"}, {"literal":"o"}, {"literal":"r"}, {"literal":"a"}, {"literal":"b"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TitleDescriptor", "symbols": ["TitleDescriptor$string$10"]},
    {"name": "TitleDescriptor$string$11", "symbols": [{"literal":"C"}, {"literal":"h"}, {"literal":"a"}, {"literal":"r"}, {"literal":"m"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TitleDescriptor", "symbols": ["TitleDescriptor$string$11"]},
    {"name": "TitleDescriptor$string$12", "symbols": [{"literal":"S"}, {"literal":"h"}, {"literal":"o"}, {"literal":"c"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TitleDescriptor", "symbols": ["TitleDescriptor$string$12"]},
    {"name": "TitleDescriptor$string$13", "symbols": [{"literal":"P"}, {"literal":"o"}, {"literal":"e"}, {"literal":"t"}, {"literal":"i"}, {"literal":"c"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TitleDescriptor", "symbols": ["TitleDescriptor$string$13"]},
    {"name": "TitleDescriptor$string$14", "symbols": [{"literal":"C"}, {"literal":"o"}, {"literal":"m"}, {"literal":"m"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TitleDescriptor", "symbols": ["TitleDescriptor$string$14"]},
    {"name": "TitleDescriptor$string$15", "symbols": [{"literal":"R"}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TitleDescriptor", "symbols": ["TitleDescriptor$string$15"]},
    {"name": "TitleDescriptor$string$16", "symbols": [{"literal":"I"}, {"literal":"n"}, {"literal":"c"}, {"literal":"o"}, {"literal":"m"}, {"literal":"p"}, {"literal":"a"}, {"literal":"r"}, {"literal":"a"}, {"literal":"b"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TitleDescriptor", "symbols": ["TitleDescriptor$string$16"]},
    {"name": "TitleDescriptor$string$17", "symbols": [{"literal":"U"}, {"literal":"n"}, {"literal":"s"}, {"literal":"u"}, {"literal":"i"}, {"literal":"t"}, {"literal":"a"}, {"literal":"b"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TitleDescriptor", "symbols": ["TitleDescriptor$string$17"]},
    {"name": "TitleDescriptor$string$18", "symbols": [{"literal":"A"}, {"literal":"d"}, {"literal":"o"}, {"literal":"r"}, {"literal":"a"}, {"literal":"b"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TitleDescriptor", "symbols": ["TitleDescriptor$string$18"]},
    {"name": "TypeTwo$string$1", "symbols": [{"literal":" "}, {"literal":"o"}, {"literal":"l"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TypeTwo", "symbols": ["TypeTwo$string$1"]},
    {"name": "TypeTwo$string$2", "symbols": [{"literal":" "}, {"literal":"n"}, {"literal":"e"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TypeTwo", "symbols": ["TypeTwo$string$2"]},
    {"name": "TypeTwo$string$3", "symbols": [{"literal":" "}, {"literal":"l"}, {"literal":"a"}, {"literal":"r"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TypeTwo", "symbols": ["TypeTwo$string$3"]},
    {"name": "TypeTwo$string$4", "symbols": [{"literal":" "}, {"literal":"d"}, {"literal":"a"}, {"literal":"r"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TypeTwo", "symbols": ["TypeTwo$string$4"]},
    {"name": "TypeTwo$string$5", "symbols": [{"literal":" "}, {"literal":"l"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TypeTwo", "symbols": ["TypeTwo$string$5"]},
    {"name": "TypeTwo$string$6", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"m"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TypeTwo", "symbols": ["TypeTwo$string$6"]},
    {"name": "TypeTwo$string$7", "symbols": [{"literal":" "}, {"literal":"p"}, {"literal":"l"}, {"literal":"u"}, {"literal":"m"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TypeTwo", "symbols": ["TypeTwo$string$7"]},
    {"name": "TypeTwo$string$8", "symbols": [{"literal":" "}, {"literal":"r"}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TypeTwo", "symbols": ["TypeTwo$string$8"]},
    {"name": "HASHTAG$string$1", "symbols": [{"literal":"#"}, {"literal":"J"}, {"literal":"a"}, {"literal":"p"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HASHTAG", "symbols": ["HASHTAG$string$1"]},
    {"name": "HASHTAG$string$2", "symbols": [{"literal":"#"}, {"literal":"N"}, {"literal":"i"}, {"literal":"h"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HASHTAG", "symbols": ["HASHTAG$string$2"]},
    {"name": "HASHTAG$string$3", "symbols": [{"literal":"#"}, {"literal":"P"}, {"literal":"o"}, {"literal":"e"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HASHTAG", "symbols": ["HASHTAG$string$3"]},
    {"name": "HASHTAG$string$4", "symbols": [{"literal":"#"}, {"literal":"P"}, {"literal":"o"}, {"literal":"e"}, {"literal":"t"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HASHTAG", "symbols": ["HASHTAG$string$4"]},
    {"name": "HASHTAG$string$5", "symbols": [{"literal":"#"}, {"literal":"L"}, {"literal":"i"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"t"}, {"literal":"u"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HASHTAG", "symbols": ["HASHTAG$string$5"]},
    {"name": "ADJNOUN", "symbols": [{"literal":"A"}, "ITEM"]},
    {"name": "ADJNOUN$ebnf$1", "symbols": ["TIMING"], "postprocess": id},
    {"name": "ADJNOUN$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ADJNOUN", "symbols": ["CONTACT", "ADJNOUN$ebnf$1"]},
    {"name": "ADJNOUN", "symbols": [{"literal":"A"}, "ITEM"]},
    {"name": "ADJNOUN$ebnf$2", "symbols": ["TIMING"], "postprocess": id},
    {"name": "ADJNOUN$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ADJNOUN", "symbols": ["CONTACT", "ADJNOUN$ebnf$2"]},
    {"name": "ADJNOUN", "symbols": [{"literal":"A"}, "ITEM"]},
    {"name": "ADJNOUN$ebnf$3", "symbols": ["TIMING"], "postprocess": id},
    {"name": "ADJNOUN$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ADJNOUN", "symbols": ["CONTACT", "ADJNOUN$ebnf$3"]},
    {"name": "ADJNOUN", "symbols": ["TIMEWHEN"]},
    {"name": "ADJNOUNa", "symbols": [{"literal":"a"}, "ITEM"]},
    {"name": "ADJNOUNb", "symbols": [{"literal":"A"}, "ITEM"]},
    {"name": "ADJNOUNb$ebnf$1", "symbols": ["TIMING"], "postprocess": id},
    {"name": "ADJNOUNb$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ADJNOUNb", "symbols": ["CONTACT", "ADJNOUNb$ebnf$1"]},
    {"name": "ADJNOUNb", "symbols": [{"literal":"A"}, "ITEM"]},
    {"name": "ADJNOUNb$ebnf$2", "symbols": ["TIMING"], "postprocess": id},
    {"name": "ADJNOUNb$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ADJNOUNb", "symbols": ["CONTACT", "ADJNOUNb$ebnf$2"]},
    {"name": "ADJNOUNb", "symbols": [{"literal":"A"}, "ITEM"]},
    {"name": "ADJNOUNb$ebnf$3", "symbols": ["TIMING"], "postprocess": id},
    {"name": "ADJNOUNb$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ADJNOUNb", "symbols": ["CONTACT", "ADJNOUNb$ebnf$3"]},
    {"name": "ITEM$ebnf$1", "symbols": ["POSSESSION"], "postprocess": id},
    {"name": "ITEM$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ITEM", "symbols": ["ITEM$ebnf$1", "PEOPLE"]},
    {"name": "ITEM$ebnf$2", "symbols": ["COLOUR"], "postprocess": id},
    {"name": "ITEM$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ITEM", "symbols": ["ITEM$ebnf$2", "OBJECT"]},
    {"name": "ITEM", "symbols": ["LITERATURE"]},
    {"name": "ITEM", "symbols": ["ANIMAL"]},
    {"name": "ITEM", "symbols": ["BIRD"]},
    {"name": "ITEM", "symbols": ["FLOWER"]},
    {"name": "SimpleItem", "symbols": ["PEOPLE"]},
    {"name": "SimpleItem$ebnf$1", "symbols": ["COLOUR"], "postprocess": id},
    {"name": "SimpleItem$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "SimpleItem", "symbols": ["SimpleItem$ebnf$1", "OBJECT"]},
    {"name": "SimpleItem", "symbols": ["ANIMAL"]},
    {"name": "SimpleItem", "symbols": ["BIRD", "WEATHER"]},
    {"name": "SimpleItem$ebnf$2", "symbols": ["COLOUR"], "postprocess": id},
    {"name": "SimpleItem$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "SimpleItem$ebnf$3", "symbols": ["TEXTURE"], "postprocess": id},
    {"name": "SimpleItem$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "SimpleItem", "symbols": ["SimpleItem$ebnf$2", "SimpleItem$ebnf$3", "CLOTHING"]},
    {"name": "SimpleItem", "symbols": ["INSTRUMENT"]},
    {"name": "SONIC$string$1", "symbols": [{"literal":" "}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"d"}, {"literal":" "}, {"literal":"b"}, {"literal":"y"}, {"literal":" "}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SONIC", "symbols": ["LITERATURE", "SONIC$string$1", "PEOPLE"]},
    {"name": "SONIC$string$2", "symbols": [{"literal":" "}, {"literal":"p"}, {"literal":"l"}, {"literal":"a"}, {"literal":"y"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"b"}, {"literal":"y"}, {"literal":" "}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SONIC", "symbols": ["INSTRUMENT", "SONIC$string$2", "PEOPLE"]},
    {"name": "VITEM$ebnf$1", "symbols": ["POSSESSION"], "postprocess": id},
    {"name": "VITEM$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "VITEM", "symbols": ["VITEM$ebnf$1", "PEOPLE"]},
    {"name": "VITEM$ebnf$2", "symbols": ["COLOUR"], "postprocess": id},
    {"name": "VITEM$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "VITEM", "symbols": ["VITEM$ebnf$2", "OBJECT"]},
    {"name": "VITEM$ebnf$3", "symbols": ["TIMING"], "postprocess": id},
    {"name": "VITEM$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "VITEM", "symbols": ["ANIMAL", "VITEM$ebnf$3"]},
    {"name": "VITEM$ebnf$4", "symbols": ["TIMING"], "postprocess": id},
    {"name": "VITEM$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "VITEM", "symbols": ["BIRD", "VITEM$ebnf$4"]},
    {"name": "VITEM$ebnf$5", "symbols": ["COLOUR"], "postprocess": id},
    {"name": "VITEM$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "VITEM$ebnf$6", "symbols": ["TEXTURE"], "postprocess": id},
    {"name": "VITEM$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "VITEM", "symbols": ["VITEM$ebnf$5", "VITEM$ebnf$6", "CLOTHING"]},
    {"name": "VITEM", "symbols": ["INSTRUMENT"]},
    {"name": "PEOPLEADJ$string$1", "symbols": [{"literal":" "}, {"literal":"o"}, {"literal":"l"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PEOPLEADJ", "symbols": ["PEOPLEADJ$string$1"]},
    {"name": "PEOPLEADJ$string$2", "symbols": [{"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PEOPLEADJ", "symbols": ["PEOPLEADJ$string$2"]},
    {"name": "PEOPLEADJ$string$3", "symbols": [{"literal":" "}, {"literal":"g"}, {"literal":"o"}, {"literal":"o"}, {"literal":"d"}, {"literal":" "}, {"literal":"l"}, {"literal":"o"}, {"literal":"o"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PEOPLEADJ", "symbols": ["PEOPLEADJ$string$3"]},
    {"name": "PEOPLEADJ$string$4", "symbols": [{"literal":" "}, {"literal":"u"}, {"literal":"g"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PEOPLEADJ", "symbols": ["PEOPLEADJ$string$4"]},
    {"name": "PEOPLEADJ$string$5", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PEOPLEADJ", "symbols": ["PEOPLEADJ$string$5"]},
    {"name": "PEOPLEADJ$string$6", "symbols": [{"literal":" "}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PEOPLEADJ", "symbols": ["PEOPLEADJ$string$6"]},
    {"name": "CONTACT$string$1", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"g"}, {"literal":"l"}, {"literal":"i"}, {"literal":"m"}, {"literal":"p"}, {"literal":"s"}, {"literal":"e"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":" "}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CONTACT", "symbols": ["CONTACT$string$1", "VITEM"]},
    {"name": "CONTACT$string$2", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"s"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":" "}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CONTACT", "symbols": ["CONTACT$string$2", "VITEM"]},
    {"name": "CONTACT$string$3", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"s"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":" "}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CONTACT", "symbols": ["CONTACT$string$3", "SONIC"]},
    {"name": "CONTACT$string$4", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"r"}, {"literal":"u"}, {"literal":"s"}, {"literal":"t"}, {"literal":"l"}, {"literal":"e"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":" "}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CONTACT$ebnf$1", "symbols": ["COLOUR"], "postprocess": id},
    {"name": "CONTACT$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "CONTACT$ebnf$2", "symbols": ["TEXTURE"], "postprocess": id},
    {"name": "CONTACT$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "CONTACT", "symbols": ["CONTACT$string$4", "CONTACT$ebnf$1", "CONTACT$ebnf$2", "CLOTHING"]},
    {"name": "CONTACT", "symbols": ["BIRDSONG", "BIRD"]},
    {"name": "TIMING$string$1", "symbols": [{"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIMING$ebnf$1", "symbols": ["WEATHER"], "postprocess": id},
    {"name": "TIMING$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "TIMING", "symbols": ["TIMING$string$1", "SEASON", "TIMING$ebnf$1"]},
    {"name": "TIMING$string$2", "symbols": [{"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIMING", "symbols": ["TIMING$string$2", "DATE"]},
    {"name": "BIRDSONG$string$1", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":" "}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BIRDSONG", "symbols": ["BIRDSONG$string$1"]},
    {"name": "BIRDSONG$string$2", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"s"}, {"literal":"o"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":" "}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BIRDSONG", "symbols": ["BIRDSONG$string$2"]},
    {"name": "BIRDSONG$string$3", "symbols": [{"literal":"A"}, {"literal":" "}, {"literal":"s"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BIRDSONG", "symbols": ["BIRDSONG$string$3"]},
    {"name": "TIMEANDWEATHER$ebnf$1", "symbols": ["TIMEODAY"], "postprocess": id},
    {"name": "TIMEANDWEATHER$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "TIMEANDWEATHER", "symbols": ["SEASON", "TIMEANDWEATHER$ebnf$1"]},
    {"name": "TIMEANDWEATHER", "symbols": ["SEASON", "WEATHER"]},
    {"name": "TIMEANDWEATHER$ebnf$2", "symbols": ["WEATHER"], "postprocess": id},
    {"name": "TIMEANDWEATHER$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "TIMEANDWEATHER", "symbols": ["TIMEODAY", "TIMEANDWEATHER$ebnf$2"]},
    {"name": "TIMEANDWEATHER", "symbols": ["WEATHER"]},
    {"name": "TIMEWHEN$string$1", "symbols": [{"literal":" "}, {"literal":"w"}, {"literal":"h"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIMEWHEN$string$2", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIMEWHEN", "symbols": ["TIME", "TIMEWHEN$string$1", "SETTINGIN", "TIMEWHEN$string$2", "EVENTSIN"]},
    {"name": "TIMEWHEN$string$3", "symbols": [{"literal":" "}, {"literal":"w"}, {"literal":"h"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIMEWHEN$string$4", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIMEWHEN", "symbols": ["TIME", "TIMEWHEN$string$3", "SETTINGOUT", "TIMEWHEN$string$4", "EVENTSOUT"]},
    {"name": "TIMEWHEN$string$5", "symbols": [{"literal":" "}, {"literal":"w"}, {"literal":"h"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIMEWHEN$string$6", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIMEWHEN", "symbols": ["TIME", "TIMEWHEN$string$5", "LETTERSENT", "TIMEWHEN$string$6", "LETTEREVENT"]},
    {"name": "TIME$string$1", "symbols": [{"literal":"O"}, {"literal":"n"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME", "symbols": ["TIME$string$1"]},
    {"name": "TIME$string$2", "symbols": [{"literal":"O"}, {"literal":"n"}, {"literal":"e"}, {"literal":" "}, {"literal":"d"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME", "symbols": ["TIME$string$2"]},
    {"name": "TIME$string$3", "symbols": [{"literal":"O"}, {"literal":"n"}, {"literal":"e"}, {"literal":" "}, {"literal":"t"}, {"literal":"i"}, {"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME", "symbols": ["TIME$string$3"]},
    {"name": "TIME$string$4", "symbols": [{"literal":"O"}, {"literal":"n"}, {"literal":"e"}, {"literal":" "}, {"literal":"d"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME", "symbols": ["TIME$string$4"]},
    {"name": "TIME$string$5", "symbols": [{"literal":"B"}, {"literal":"a"}, {"literal":"c"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME", "symbols": ["TIME$string$5"]},
    {"name": "TIME$string$6", "symbols": [{"literal":"I"}, {"literal":"n"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME", "symbols": ["TIME$string$6", "DATE"]},
    {"name": "SETTINGIN$string$1", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"E"}, {"literal":"m"}, {"literal":"p"}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}, {"literal":"s"}, {"literal":" "}, {"literal":"w"}, {"literal":"a"}, {"literal":"s"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"n"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SETTINGIN", "symbols": ["SETTINGIN$string$1"]},
    {"name": "SETTINGIN$string$2", "symbols": [{"literal":" "}, {"literal":"I"}, {"literal":" "}, {"literal":"w"}, {"literal":"a"}, {"literal":"s"}, {"literal":" "}, {"literal":"n"}, {"literal":"e"}, {"literal":"w"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"p"}, {"literal":"a"}, {"literal":"l"}, {"literal":"a"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SETTINGIN", "symbols": ["SETTINGIN$string$2"]},
    {"name": "SETTINGIN$string$3", "symbols": [{"literal":" "}, {"literal":"i"}, {"literal":"t"}, {"literal":" "}, {"literal":"w"}, {"literal":"a"}, {"literal":"s"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SETTINGIN$string$4", "symbols": [{"literal":" "}, {"literal":"f"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"a"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SETTINGIN", "symbols": ["SETTINGIN$string$3", "FESTIVAL", "SETTINGIN$string$4"]},
    {"name": "SETTINGIN$string$5", "symbols": [{"literal":" "}, {"literal":"m"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SETTINGIN$string$6", "symbols": [{"literal":" "}, {"literal":"w"}, {"literal":"a"}, {"literal":"s"}, {"literal":" "}, {"literal":"v"}, {"literal":"i"}, {"literal":"s"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SETTINGIN", "symbols": ["SETTINGIN$string$5", "RELATIVE", "SETTINGIN$string$6"]},
    {"name": "SETTINGIN$string$7", "symbols": [{"literal":" "}, {"literal":"w"}, {"literal":"e"}, {"literal":" "}, {"literal":"w"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"m"}, {"literal":"p"}, {"literal":"s"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"p"}, {"literal":"o"}, {"literal":"e"}, {"literal":"m"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SETTINGIN", "symbols": ["SETTINGIN$string$7"]},
    {"name": "SETTINGIN$string$8", "symbols": [{"literal":" "}, {"literal":"w"}, {"literal":"e"}, {"literal":" "}, {"literal":"w"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}, {"literal":"c"}, {"literal":"h"}, {"literal":"o"}, {"literal":"o"}, {"literal":"s"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":"c"}, {"literal":"e"}, {"literal":"n"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SETTINGIN", "symbols": ["SETTINGIN$string$8"]},
    {"name": "SETTINGIN$string$9", "symbols": [{"literal":" "}, {"literal":"w"}, {"literal":"a"}, {"literal":"s"}, {"literal":" "}, {"literal":"j"}, {"literal":"u"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"l"}, {"literal":"e"}, {"literal":"a"}, {"literal":"v"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SETTINGIN", "symbols": ["RELATIVE", "SETTINGIN$string$9"]},
    {"name": "SETTINGOUT$string$1", "symbols": [{"literal":" "}, {"literal":"I"}, {"literal":" "}, {"literal":"w"}, {"literal":"a"}, {"literal":"s"}, {"literal":" "}, {"literal":"t"}, {"literal":"r"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}, {"literal":"l"}, {"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SETTINGOUT", "symbols": ["SETTINGOUT$string$1"]},
    {"name": "SETTINGOUT$string$2", "symbols": [{"literal":" "}, {"literal":"I"}, {"literal":" "}, {"literal":"w"}, {"literal":"a"}, {"literal":"s"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SETTINGOUT", "symbols": ["SETTINGOUT$string$2", "PLACEOUT"]},
    {"name": "FESTIVAL$string$1", "symbols": [{"literal":" "}, {"literal":"T"}, {"literal":"a"}, {"literal":"n"}, {"literal":"a"}, {"literal":"b"}, {"literal":"a"}, {"literal":"t"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FESTIVAL", "symbols": ["FESTIVAL$string$1"]},
    {"name": "FESTIVAL$string$2", "symbols": [{"literal":" "}, {"literal":"M"}, {"literal":"i"}, {"literal":"b"}, {"literal":"u"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FESTIVAL", "symbols": ["FESTIVAL$string$2"]},
    {"name": "FESTIVAL$string$3", "symbols": [{"literal":" "}, {"literal":"O"}, {"literal":"b"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FESTIVAL", "symbols": ["FESTIVAL$string$3"]},
    {"name": "FESTIVAL$string$4", "symbols": [{"literal":" "}, {"literal":"N"}, {"literal":"e"}, {"literal":"w"}, {"literal":" "}, {"literal":"y"}, {"literal":"e"}, {"literal":"a"}, {"literal":"r"}, {"literal":"'"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FESTIVAL", "symbols": ["FESTIVAL$string$4"]},
    {"name": "FESTIVAL$string$5", "symbols": [{"literal":" "}, {"literal":"f"}, {"literal":"l"}, {"literal":"o"}, {"literal":"w"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FESTIVAL", "symbols": ["FESTIVAL$string$5"]},
    {"name": "EVENTSIN$string$1", "symbols": [{"literal":" "}, {"literal":"I"}, {"literal":" "}, {"literal":"s"}, {"literal":"a"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EVENTSIN", "symbols": ["EVENTSIN$string$1", "PALACEEVENT"]},
    {"name": "EVENTSOUT$string$1", "symbols": [{"literal":" "}, {"literal":"I"}, {"literal":" "}, {"literal":"s"}, {"literal":"a"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EVENTSOUT", "symbols": ["EVENTSOUT$string$1", "DISTANTEVENT"]},
    {"name": "PALACEEVENT$string$1", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"t"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PALACEEVENT", "symbols": ["PALACEEVENT$string$1", "LOCATIONIN"]},
    {"name": "PALACEEVENT$string$2", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"n"}, {"literal":"o"}, {"literal":"w"}, {"literal":" "}, {"literal":"f"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PALACEEVENT", "symbols": ["PALACEEVENT$string$2", "LOCATIONIN"]},
    {"name": "PALACEEVENT$string$3", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"s"}, {"literal":"e"}, {"literal":"r"}, {"literal":"v"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":" "}, {"literal":"s"}, {"literal":"w"}, {"literal":"e"}, {"literal":"e"}, {"literal":"p"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PALACEEVENT", "symbols": ["PALACEEVENT$string$3", "LOCATIONIN"]},
    {"name": "PALACEEVENT$string$4", "symbols": [{"literal":" "}, {"literal":"m"}, {"literal":"i"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"h"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PALACEEVENT", "symbols": ["PALACEEVENT$string$4"]},
    {"name": "PALACEEVENT$string$5", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"n"}, {"literal":"k"}, {"literal":" "}, {"literal":"b"}, {"literal":"u"}, {"literal":"r"}, {"literal":"n"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":"c"}, {"literal":"e"}, {"literal":"n"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PALACEEVENT", "symbols": ["PALACEEVENT$string$5"]},
    {"name": "PALACEEVENT$string$6", "symbols": [{"literal":" "}, {"literal":"c"}, {"literal":"r"}, {"literal":"a"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}, {"literal":" "}, {"literal":"f"}, {"literal":"l"}, {"literal":"y"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PALACEEVENT", "symbols": ["PALACEEVENT$string$6", "LOCATIONIN"]},
    {"name": "DISTANTEVENT$string$1", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"n"}, {"literal":"o"}, {"literal":"w"}, {"literal":" "}, {"literal":"f"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DISTANTEVENT", "symbols": ["DISTANTEVENT$string$1", "LOCATIONOUT"]},
    {"name": "DISTANTEVENT$string$2", "symbols": [{"literal":" "}, {"literal":"m"}, {"literal":"i"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DISTANTEVENT", "symbols": ["DISTANTEVENT$string$2", "LOCATIONOUT"]},
    {"name": "DISTANTEVENT$string$3", "symbols": [{"literal":" "}, {"literal":"c"}, {"literal":"r"}, {"literal":"a"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}, {"literal":" "}, {"literal":"f"}, {"literal":"l"}, {"literal":"y"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DISTANTEVENT", "symbols": ["DISTANTEVENT$string$3", "LOCATIONOUT"]},
    {"name": "LOCATIONIN$string$1", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"p"}, {"literal":"a"}, {"literal":"l"}, {"literal":"a"}, {"literal":"c"}, {"literal":"e"}, {"literal":" "}, {"literal":"g"}, {"literal":"a"}, {"literal":"r"}, {"literal":"d"}, {"literal":"e"}, {"literal":"n"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATIONIN", "symbols": ["LOCATIONIN$string$1"]},
    {"name": "LOCATIONIN$string$2", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"b"}, {"literal":"a"}, {"literal":"c"}, {"literal":"k"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"r"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATIONIN", "symbols": ["LOCATIONIN$string$2"]},
    {"name": "LOCATIONIN$string$3", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"t"}, {"literal":"e"}, {"literal":"m"}, {"literal":"p"}, {"literal":"l"}, {"literal":"e"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"w"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATIONIN", "symbols": ["LOCATIONIN$string$3"]},
    {"name": "LOCATIONIN$string$4", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"p"}, {"literal":"a"}, {"literal":"l"}, {"literal":"a"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATIONIN", "symbols": ["LOCATIONIN$string$4"]},
    {"name": "LOCATIONIN$string$5", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"E"}, {"literal":"m"}, {"literal":"p"}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}, {"literal":"s"}, {"literal":"'"}, {"literal":"s"}, {"literal":" "}, {"literal":"q"}, {"literal":"u"}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATIONIN", "symbols": ["LOCATIONIN$string$5"]},
    {"name": "LOCATIONIN$string$6", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"g"}, {"literal":"u"}, {"literal":"a"}, {"literal":"r"}, {"literal":"d"}, {"literal":"h"}, {"literal":"o"}, {"literal":"u"}, {"literal":"s"}, {"literal":"e"}, {"literal":" "}, {"literal":"b"}, {"literal":"y"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"f"}, {"literal":"r"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":" "}, {"literal":"g"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATIONIN", "symbols": ["LOCATIONIN$string$6"]},
    {"name": "LOCATIONIN$string$7", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"r"}, {"literal":"i"}, {"literal":"s"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATIONIN", "symbols": ["LOCATIONIN$string$7", "LOCATIONIN"]},
    {"name": "LOCATIONOUT$string$1", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"h"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATIONOUT", "symbols": ["LOCATIONOUT$string$1"]},
    {"name": "LOCATIONOUT$string$2", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"v"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"e"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATIONOUT", "symbols": ["LOCATIONOUT$string$2"]},
    {"name": "LOCATIONOUT$string$3", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"v"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":"a"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATIONOUT", "symbols": ["LOCATIONOUT$string$3"]},
    {"name": "LOCATIONOUT$string$4", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"r"}, {"literal":"o"}, {"literal":"a"}, {"literal":"d"}, {"literal":"w"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATIONOUT", "symbols": ["LOCATIONOUT$string$4"]},
    {"name": "LOCATIONOUT$string$5", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATIONOUT", "symbols": ["LOCATIONOUT$string$5"]},
    {"name": "PLACEOUT$string$1", "symbols": [{"literal":" "}, {"literal":"O"}, {"literal":"j"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACEOUT", "symbols": ["PLACEOUT$string$1"]},
    {"name": "PLACEOUT$string$2", "symbols": [{"literal":" "}, {"literal":"H"}, {"literal":"y"}, {"literal":"u"}, {"literal":"g"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACEOUT", "symbols": ["PLACEOUT$string$2"]},
    {"name": "PLACEOUT$string$3", "symbols": [{"literal":" "}, {"literal":"N"}, {"literal":"a"}, {"literal":"r"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACEOUT", "symbols": ["PLACEOUT$string$3"]},
    {"name": "PLACEOUT$string$4", "symbols": [{"literal":" "}, {"literal":"I"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACEOUT", "symbols": ["PLACEOUT$string$4"]},
    {"name": "LETTERSENT$string$1", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":" "}, {"literal":"m"}, {"literal":"e"}, {"literal":" "}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LETTERSENT", "symbols": ["SENDER", "LETTERSENT$string$1", "LETTER"]},
    {"name": "LETTEREVENT$string$1", "symbols": [{"literal":" "}, {"literal":"m"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LETTEREVENT$string$2", "symbols": [{"literal":" "}, {"literal":"p"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"d"}, {"literal":" "}, {"literal":"i"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LETTEREVENT", "symbols": ["LETTEREVENT$string$1", "RELATIVE", "LETTEREVENT$string$2"]},
    {"name": "LETTEREVENT", "symbols": ["LETTERA", "LETTERCONDITION"]},
    {"name": "SENDER$string$1", "symbols": [{"literal":" "}, {"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"l"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENDER", "symbols": ["SENDER$string$1"]},
    {"name": "SENDER$string$2", "symbols": [{"literal":" "}, {"literal":"K"}, {"literal":"i"}, {"literal":"y"}, {"literal":"o"}, {"literal":"n"}, {"literal":"a"}, {"literal":"r"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENDER", "symbols": ["SENDER$string$2"]},
    {"name": "SENDER$string$3", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"E"}, {"literal":"m"}, {"literal":"p"}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENDER", "symbols": ["SENDER$string$3"]},
    {"name": "SENDER$string$4", "symbols": [{"literal":" "}, {"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"f"}, {"literal":"r"}, {"literal":"i"}, {"literal":"e"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENDER", "symbols": ["SENDER$string$4"]},
    {"name": "SENDER$string$5", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"c"}, {"literal":"e"}, {"literal":"r"}, {"literal":"t"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"l"}, {"literal":"e"}, {"literal":"m"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENDER", "symbols": ["SENDER$string$5"]},
    {"name": "LETTER$string$1", "symbols": [{"literal":" "}, {"literal":"l"}, {"literal":"e"}, {"literal":"t"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LETTER", "symbols": ["LETTER$string$1"]},
    {"name": "LETTER$string$2", "symbols": [{"literal":" "}, {"literal":"p"}, {"literal":"o"}, {"literal":"e"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LETTER", "symbols": ["LETTER$string$2"]},
    {"name": "LETTER$string$3", "symbols": [{"literal":" "}, {"literal":"n"}, {"literal":"o"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LETTER", "symbols": ["LETTER$string$3"]},
    {"name": "LETTERA$string$1", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"p"}, {"literal":"a"}, {"literal":"p"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LETTERA", "symbols": ["LETTERA$string$1"]},
    {"name": "LETTERA$string$2", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"e"}, {"literal":"n"}, {"literal":"v"}, {"literal":"e"}, {"literal":"l"}, {"literal":"o"}, {"literal":"p"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LETTERA", "symbols": ["LETTERA$string$2"]},
    {"name": "LETTERA$string$3", "symbols": [{"literal":" "}, {"literal":"i"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LETTERA", "symbols": ["LETTERA$string$3"]},
    {"name": "LETTERCONDITION$string$1", "symbols": [{"literal":" "}, {"literal":"w"}, {"literal":"a"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LETTERCONDITION$string$2", "symbols": [{"literal":" "}, {"literal":"w"}, {"literal":"i"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LETTERCONDITION", "symbols": ["LETTERCONDITION$string$1", "WRAPPED", "LETTERCONDITION$string$2", "FLOWER"]},
    {"name": "WRAPPED$string$1", "symbols": [{"literal":" "}, {"literal":"w"}, {"literal":"r"}, {"literal":"a"}, {"literal":"p"}, {"literal":"p"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WRAPPED", "symbols": ["WRAPPED$string$1"]},
    {"name": "WRAPPED$string$2", "symbols": [{"literal":" "}, {"literal":"w"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WRAPPED", "symbols": ["WRAPPED$string$2"]},
    {"name": "WRAPPED$string$3", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"i"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WRAPPED", "symbols": ["WRAPPED$string$3"]},
    {"name": "WRAPPED$string$4", "symbols": [{"literal":" "}, {"literal":"b"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WRAPPED", "symbols": ["WRAPPED$string$4"]},
    {"name": "WRAPPED$string$5", "symbols": [{"literal":" "}, {"literal":"w"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WRAPPED", "symbols": ["WRAPPED$string$5"]},
    {"name": "COLOUR$string$1", "symbols": [{"literal":" "}, {"literal":"r"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COLOUR", "symbols": ["COLOUR$string$1"]},
    {"name": "COLOUR$string$2", "symbols": [{"literal":" "}, {"literal":"y"}, {"literal":"e"}, {"literal":"l"}, {"literal":"l"}, {"literal":"o"}, {"literal":"w"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COLOUR", "symbols": ["COLOUR$string$2"]},
    {"name": "COLOUR$string$3", "symbols": [{"literal":" "}, {"literal":"p"}, {"literal":"u"}, {"literal":"r"}, {"literal":"p"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COLOUR", "symbols": ["COLOUR$string$3"]},
    {"name": "COLOUR$string$4", "symbols": [{"literal":" "}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COLOUR", "symbols": ["COLOUR$string$4"]},
    {"name": "COLOUR$string$5", "symbols": [{"literal":" "}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COLOUR", "symbols": ["COLOUR$string$5"]},
    {"name": "COLOUR$string$6", "symbols": [{"literal":" "}, {"literal":"r"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COLOUR", "symbols": ["COLOUR$string$6"]},
    {"name": "COLOUR$string$7", "symbols": [{"literal":" "}, {"literal":"b"}, {"literal":"l"}, {"literal":"u"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COLOUR", "symbols": ["COLOUR$string$7"]},
    {"name": "COLOUR$string$8", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"h"}, {"literal":"a"}, {"literal":"d"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COLOUR", "symbols": ["COLOUR$string$8"]},
    {"name": "COLOUR$string$9", "symbols": [{"literal":" "}, {"literal":"f"}, {"literal":"l"}, {"literal":"o"}, {"literal":"w"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COLOUR", "symbols": ["COLOUR$string$9"]},
    {"name": "COLOUR$string$10", "symbols": [{"literal":" "}, {"literal":"w"}, {"literal":"h"}, {"literal":"i"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COLOUR", "symbols": ["COLOUR$string$10"]},
    {"name": "COLOUR$string$11", "symbols": [{"literal":" "}, {"literal":"p"}, {"literal":"a"}, {"literal":"t"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":"n"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COLOUR", "symbols": ["COLOUR$string$11"]},
    {"name": "COLOUR$string$12", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"i"}, {"literal":"l"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COLOUR", "symbols": ["COLOUR$string$12"]},
    {"name": "COLOUR$string$13", "symbols": [{"literal":" "}, {"literal":"g"}, {"literal":"o"}, {"literal":"l"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COLOUR", "symbols": ["COLOUR$string$13"]},
    {"name": "COLOUR$string$14", "symbols": [{"literal":" "}, {"literal":"b"}, {"literal":"r"}, {"literal":"o"}, {"literal":"n"}, {"literal":"z"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COLOUR", "symbols": ["COLOUR$string$14"]},
    {"name": "SEASON$string$1", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"p"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SEASON", "symbols": ["SEASON$string$1"]},
    {"name": "SEASON$string$2", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"u"}, {"literal":"m"}, {"literal":"m"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SEASON", "symbols": ["SEASON$string$2"]},
    {"name": "SEASON$string$3", "symbols": [{"literal":" "}, {"literal":"w"}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SEASON", "symbols": ["SEASON$string$3"]},
    {"name": "SEASON$string$4", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":"u"}, {"literal":"t"}, {"literal":"u"}, {"literal":"m"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SEASON", "symbols": ["SEASON$string$4"]},
    {"name": "TEXTURE$string$1", "symbols": [{"literal":" "}, {"literal":"C"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TEXTURE", "symbols": ["TEXTURE$string$1"]},
    {"name": "TEXTURE$string$2", "symbols": [{"literal":" "}, {"literal":"K"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TEXTURE", "symbols": ["TEXTURE$string$2"]},
    {"name": "TEXTURE$string$3", "symbols": [{"literal":" "}, {"literal":"n"}, {"literal":"o"}, {"literal":"r"}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TEXTURE", "symbols": ["TEXTURE$string$3"]},
    {"name": "TEXTURE$string$4", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"m"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TEXTURE", "symbols": ["TEXTURE$string$4"]},
    {"name": "TEXTURE$string$5", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"i"}, {"literal":"l"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TEXTURE", "symbols": ["TEXTURE$string$5"]},
    {"name": "DATE$string$1", "symbols": [{"literal":" "}, {"literal":"f"}, {"literal":"i"}, {"literal":"r"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DATE", "symbols": ["DATE$string$1"]},
    {"name": "DATE$string$2", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"e"}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DATE", "symbols": ["DATE$string$2"]},
    {"name": "DATE$string$3", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"r"}, {"literal":"d"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DATE", "symbols": ["DATE$string$3"]},
    {"name": "DATE$string$4", "symbols": [{"literal":" "}, {"literal":"f"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"t"}, {"literal":"h"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DATE", "symbols": ["DATE$string$4"]},
    {"name": "DATE$string$5", "symbols": [{"literal":" "}, {"literal":"f"}, {"literal":"i"}, {"literal":"f"}, {"literal":"t"}, {"literal":"h"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DATE", "symbols": ["DATE$string$5"]},
    {"name": "DATE$string$6", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"i"}, {"literal":"x"}, {"literal":"t"}, {"literal":"h"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DATE", "symbols": ["DATE$string$6"]},
    {"name": "DATE$string$7", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"h"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DATE", "symbols": ["DATE$string$7"]},
    {"name": "DATE$string$8", "symbols": [{"literal":" "}, {"literal":"e"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":"h"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DATE", "symbols": ["DATE$string$8"]},
    {"name": "DATE$string$9", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"h"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DATE", "symbols": ["DATE$string$9"]},
    {"name": "POSSESSION$string$1", "symbols": [{"literal":"'"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSSESSION", "symbols": ["POSESSOR", "POSSESSION$string$1"]},
    {"name": "PEOPLE$ebnf$1", "symbols": ["PEOPLEADJ"], "postprocess": id},
    {"name": "PEOPLE$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "PEOPLE$string$1", "symbols": [{"literal":" "}, {"literal":"l"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PEOPLE", "symbols": ["PEOPLE$ebnf$1", "PEOPLE$string$1"]},
    {"name": "PEOPLE$ebnf$2", "symbols": ["PEOPLEADJ"], "postprocess": id},
    {"name": "PEOPLE$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "PEOPLE$string$2", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"e"}, {"literal":"r"}, {"literal":"v"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PEOPLE", "symbols": ["PEOPLE$ebnf$2", "PEOPLE$string$2"]},
    {"name": "PEOPLE$ebnf$3", "symbols": ["PEOPLEADJ"], "postprocess": id},
    {"name": "PEOPLE$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "PEOPLE$string$3", "symbols": [{"literal":" "}, {"literal":"g"}, {"literal":"i"}, {"literal":"r"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PEOPLE", "symbols": ["PEOPLE$ebnf$3", "PEOPLE$string$3"]},
    {"name": "PEOPLE$ebnf$4", "symbols": ["PEOPLEADJ"], "postprocess": id},
    {"name": "PEOPLE$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "PEOPLE$string$4", "symbols": [{"literal":" "}, {"literal":"b"}, {"literal":"o"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PEOPLE", "symbols": ["PEOPLE$ebnf$4", "PEOPLE$string$4"]},
    {"name": "PEOPLE$ebnf$5", "symbols": ["PEOPLEADJ"], "postprocess": id},
    {"name": "PEOPLE$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "PEOPLE$string$5", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"i"}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PEOPLE", "symbols": ["PEOPLE$ebnf$5", "PEOPLE$string$5"]},
    {"name": "PEOPLE$ebnf$6", "symbols": ["PEOPLEADJ"], "postprocess": id},
    {"name": "PEOPLE$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "PEOPLE$string$6", "symbols": [{"literal":" "}, {"literal":"l"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PEOPLE", "symbols": ["PEOPLE$ebnf$6", "PEOPLE$string$6"]},
    {"name": "PEOPLE$string$7", "symbols": [{"literal":" "}, {"literal":"f"}, {"literal":"r"}, {"literal":"i"}, {"literal":"e"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PEOPLE", "symbols": ["PEOPLE$string$7"]},
    {"name": "PEOPLE$string$8", "symbols": [{"literal":" "}, {"literal":"p"}, {"literal":"e"}, {"literal":"a"}, {"literal":"s"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PEOPLE", "symbols": ["PEOPLE$string$8"]},
    {"name": "PEOPLE$string$9", "symbols": [{"literal":" "}, {"literal":"p"}, {"literal":"r"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PEOPLE", "symbols": ["PEOPLE$string$9"]},
    {"name": "PEOPLE", "symbols": ["POSESSOR"]},
    {"name": "PEOPLE", "symbols": ["RELATIVE"]},
    {"name": "POSESSOR$string$1", "symbols": [{"literal":" "}, {"literal":"l"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSESSOR", "symbols": ["POSESSOR$string$1"]},
    {"name": "POSESSOR$string$2", "symbols": [{"literal":" "}, {"literal":"l"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSESSOR", "symbols": ["POSESSOR$string$2"]},
    {"name": "POSESSOR$string$3", "symbols": [{"literal":" "}, {"literal":"f"}, {"literal":"r"}, {"literal":"i"}, {"literal":"e"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSESSOR", "symbols": ["POSESSOR$string$3"]},
    {"name": "POSESSOR$string$4", "symbols": [{"literal":" "}, {"literal":"g"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}, {"literal":"n"}, {"literal":"o"}, {"literal":"r"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSESSOR", "symbols": ["POSESSOR$string$4", "LOCATIONOUT"]},
    {"name": "POSESSOR$string$5", "symbols": [{"literal":" "}, {"literal":"p"}, {"literal":"r"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSESSOR", "symbols": ["POSESSOR$string$5"]},
    {"name": "RELATIVE$string$1", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"i"}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RELATIVE", "symbols": ["RELATIVE$string$1"]},
    {"name": "RELATIVE$string$2", "symbols": [{"literal":" "}, {"literal":"l"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RELATIVE", "symbols": ["RELATIVE$string$2"]},
    {"name": "RELATIVE$string$3", "symbols": [{"literal":" "}, {"literal":"b"}, {"literal":"r"}, {"literal":"o"}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RELATIVE", "symbols": ["RELATIVE$string$3"]},
    {"name": "RELATIVE$string$4", "symbols": [{"literal":" "}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"l"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RELATIVE", "symbols": ["RELATIVE$string$4"]},
    {"name": "RELATIVE$string$5", "symbols": [{"literal":" "}, {"literal":"d"}, {"literal":"a"}, {"literal":"u"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RELATIVE", "symbols": ["RELATIVE$string$5"]},
    {"name": "RELATIVE$string$6", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"e"}, {"literal":"r"}, {"literal":"v"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RELATIVE", "symbols": ["RELATIVE$string$6"]},
    {"name": "RELATIVE$string$7", "symbols": [{"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RELATIVE", "symbols": ["RELATIVE$string$7"]},
    {"name": "OBJECT$string$1", "symbols": [{"literal":" "}, {"literal":"b"}, {"literal":"o"}, {"literal":"x"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$1"]},
    {"name": "OBJECT$string$2", "symbols": [{"literal":" "}, {"literal":"e"}, {"literal":"n"}, {"literal":"v"}, {"literal":"e"}, {"literal":"l"}, {"literal":"o"}, {"literal":"p"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$2"]},
    {"name": "OBJECT$string$3", "symbols": [{"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":"c"}, {"literal":"e"}, {"literal":"n"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$3"]},
    {"name": "OBJECT$string$4", "symbols": [{"literal":" "}, {"literal":"f"}, {"literal":"l"}, {"literal":"o"}, {"literal":"w"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$4"]},
    {"name": "OBJECT$string$5", "symbols": [{"literal":" "}, {"literal":"v"}, {"literal":"a"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$5"]},
    {"name": "OBJECT$string$6", "symbols": [{"literal":" "}, {"literal":"c"}, {"literal":"u"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$6"]},
    {"name": "OBJECT$string$7", "symbols": [{"literal":" "}, {"literal":"f"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$7"]},
    {"name": "OBJECT$string$8", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"c"}, {"literal":"r"}, {"literal":"o"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$8"]},
    {"name": "OBJECT$string$9", "symbols": [{"literal":" "}, {"literal":"p"}, {"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$9"]},
    {"name": "OBJECT$string$10", "symbols": [{"literal":" "}, {"literal":"r"}, {"literal":"a"}, {"literal":"k"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$10"]},
    {"name": "LITERATURE$string$1", "symbols": [{"literal":" "}, {"literal":"l"}, {"literal":"e"}, {"literal":"t"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LITERATURE", "symbols": ["LITERATURE$string$1"]},
    {"name": "LITERATURE$string$2", "symbols": [{"literal":" "}, {"literal":"p"}, {"literal":"o"}, {"literal":"e"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LITERATURE", "symbols": ["LITERATURE$string$2"]},
    {"name": "LITERATURE$string$3", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"u"}, {"literal":"t"}, {"literal":"r"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LITERATURE", "symbols": ["LITERATURE$string$3"]},
    {"name": "LITERATURE$string$4", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"a"}, {"literal":"n"}, {"literal":"k"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LITERATURE", "symbols": ["LITERATURE$string$4"]},
    {"name": "INSTRUMENT$string$1", "symbols": [{"literal":" "}, {"literal":"k"}, {"literal":"o"}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INSTRUMENT", "symbols": ["INSTRUMENT$string$1"]},
    {"name": "INSTRUMENT$string$2", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"h"}, {"literal":"a"}, {"literal":"m"}, {"literal":"i"}, {"literal":"n"}, {"literal":"s"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INSTRUMENT", "symbols": ["INSTRUMENT$string$2"]},
    {"name": "INSTRUMENT$string$3", "symbols": [{"literal":" "}, {"literal":"f"}, {"literal":"l"}, {"literal":"u"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INSTRUMENT", "symbols": ["INSTRUMENT$string$3"]},
    {"name": "ANIMAL$string$1", "symbols": [{"literal":" "}, {"literal":"g"}, {"literal":"o"}, {"literal":"o"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANIMAL", "symbols": ["ANIMAL$string$1"]},
    {"name": "ANIMAL$string$2", "symbols": [{"literal":" "}, {"literal":"o"}, {"literal":"x"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANIMAL", "symbols": ["ANIMAL$string$2"]},
    {"name": "ANIMAL$string$3", "symbols": [{"literal":" "}, {"literal":"c"}, {"literal":"r"}, {"literal":"a"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANIMAL", "symbols": ["ANIMAL$string$3"]},
    {"name": "ANIMAL$string$4", "symbols": [{"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"r"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANIMAL", "symbols": ["ANIMAL$string$4"]},
    {"name": "ANIMAL$string$5", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"u"}, {"literal":"r"}, {"literal":"t"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANIMAL", "symbols": ["ANIMAL$string$5"]},
    {"name": "ANIMAL$string$6", "symbols": [{"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANIMAL", "symbols": ["ANIMAL$string$6"]},
    {"name": "ANIMAL$string$7", "symbols": [{"literal":" "}, {"literal":"d"}, {"literal":"o"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANIMAL", "symbols": ["ANIMAL$string$7"]},
    {"name": "ANIMAL$string$8", "symbols": [{"literal":" "}, {"literal":"c"}, {"literal":"r"}, {"literal":"o"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANIMAL", "symbols": ["ANIMAL$string$8"]},
    {"name": "ANIMAL$string$9", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"a"}, {"literal":"l"}, {"literal":"m"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANIMAL", "symbols": ["ANIMAL$string$9"]},
    {"name": "ANIMAL$string$10", "symbols": [{"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"n"}, {"literal":"k"}, {"literal":"e"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANIMAL", "symbols": ["ANIMAL$string$10"]},
    {"name": "ANIMAL$string$11", "symbols": [{"literal":" "}, {"literal":"b"}, {"literal":"e"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANIMAL", "symbols": ["ANIMAL$string$11"]},
    {"name": "ANIMAL$string$12", "symbols": [{"literal":" "}, {"literal":"b"}, {"literal":"o"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANIMAL", "symbols": ["ANIMAL$string$12"]},
    {"name": "ANIMAL$string$13", "symbols": [{"literal":" "}, {"literal":"n"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"a"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANIMAL", "symbols": ["ANIMAL$string$13"]},
    {"name": "ANIMAL$string$14", "symbols": [{"literal":" "}, {"literal":"e"}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANIMAL", "symbols": ["ANIMAL$string$14"]},
    {"name": "BIRD$string$1", "symbols": [{"literal":" "}, {"literal":"g"}, {"literal":"o"}, {"literal":"o"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BIRD", "symbols": ["BIRD$string$1"]},
    {"name": "BIRD$string$2", "symbols": [{"literal":" "}, {"literal":"c"}, {"literal":"r"}, {"literal":"a"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BIRD", "symbols": ["BIRD$string$2"]},
    {"name": "BIRD$string$3", "symbols": [{"literal":" "}, {"literal":"c"}, {"literal":"r"}, {"literal":"o"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BIRD", "symbols": ["BIRD$string$3"]},
    {"name": "BIRD$string$4", "symbols": [{"literal":" "}, {"literal":"n"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"a"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BIRD", "symbols": ["BIRD$string$4"]},
    {"name": "BIRD$string$5", "symbols": [{"literal":" "}, {"literal":"e"}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BIRD", "symbols": ["BIRD$string$5"]},
    {"name": "TIMEODAY$string$1", "symbols": [{"literal":" "}, {"literal":"n"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIMEODAY", "symbols": ["TIMEODAY$string$1"]},
    {"name": "TIMEODAY$string$2", "symbols": [{"literal":" "}, {"literal":"d"}, {"literal":"a"}, {"literal":"w"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIMEODAY", "symbols": ["TIMEODAY$string$2"]},
    {"name": "TIMEODAY$string$3", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"w"}, {"literal":"i"}, {"literal":"l"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIMEODAY", "symbols": ["TIMEODAY$string$3"]},
    {"name": "TIMEODAY$string$4", "symbols": [{"literal":" "}, {"literal":"d"}, {"literal":"u"}, {"literal":"s"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIMEODAY", "symbols": ["TIMEODAY$string$4"]},
    {"name": "TIMEODAY$string$5", "symbols": [{"literal":" "}, {"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIMEODAY", "symbols": ["TIMEODAY$string$5"]},
    {"name": "WEATHER$string$1", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"n"}, {"literal":"o"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WEATHER", "symbols": ["WEATHER$string$1"]},
    {"name": "WEATHER$string$2", "symbols": [{"literal":" "}, {"literal":"r"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WEATHER", "symbols": ["WEATHER$string$2"]},
    {"name": "WEATHER$string$3", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"u"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WEATHER", "symbols": ["WEATHER$string$3"]},
    {"name": "WEATHER$string$4", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"h"}, {"literal":"a"}, {"literal":"d"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WEATHER", "symbols": ["WEATHER$string$4"]},
    {"name": "WEATHER$string$5", "symbols": [{"literal":" "}, {"literal":"c"}, {"literal":"l"}, {"literal":"o"}, {"literal":"u"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WEATHER", "symbols": ["WEATHER$string$5"]},
    {"name": "WEATHER$string$6", "symbols": [{"literal":" "}, {"literal":"m"}, {"literal":"i"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WEATHER", "symbols": ["WEATHER$string$6"]},
    {"name": "WEATHER$string$7", "symbols": [{"literal":" "}, {"literal":"f"}, {"literal":"o"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WEATHER", "symbols": ["WEATHER$string$7"]},
    {"name": "CLOTHING$string$1", "symbols": [{"literal":" "}, {"literal":"r"}, {"literal":"o"}, {"literal":"b"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CLOTHING", "symbols": ["CLOTHING$string$1"]},
    {"name": "CLOTHING$string$2", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"l"}, {"literal":"e"}, {"literal":"e"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CLOTHING", "symbols": ["CLOTHING$string$2"]},
    {"name": "CLOTHING$string$3", "symbols": [{"literal":" "}, {"literal":"g"}, {"literal":"o"}, {"literal":"w"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CLOTHING", "symbols": ["CLOTHING$string$3"]},
    {"name": "CLOTHING$string$4", "symbols": [{"literal":" "}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CLOTHING", "symbols": ["CLOTHING$string$4"]},
    {"name": "CLOTHING$string$5", "symbols": [{"literal":" "}, {"literal":"v"}, {"literal":"e"}, {"literal":"i"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CLOTHING", "symbols": ["CLOTHING$string$5"]},
    {"name": "CLOTHING$string$6", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"h"}, {"literal":"a"}, {"literal":"w"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CLOTHING", "symbols": ["CLOTHING$string$6"]},
    {"name": "CLOTHING$string$7", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"l"}, {"literal":"i"}, {"literal":"p"}, {"literal":"p"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CLOTHING", "symbols": ["CLOTHING$string$7"]},
    {"name": "CLOTHING$string$8", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":"a"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CLOTHING", "symbols": ["CLOTHING$string$8"]},
    {"name": "FLOWER$string$1", "symbols": [{"literal":" "}, {"literal":"g"}, {"literal":"r"}, {"literal":"a"}, {"literal":"s"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FLOWER", "symbols": ["FLOWER$string$1"]},
    {"name": "FLOWER$string$2", "symbols": [{"literal":" "}, {"literal":"p"}, {"literal":"e"}, {"literal":"o"}, {"literal":"n"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FLOWER", "symbols": ["FLOWER$string$2"]},
    {"name": "FLOWER$string$3", "symbols": [{"literal":" "}, {"literal":"i"}, {"literal":"r"}, {"literal":"i"}, {"literal":"s"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FLOWER", "symbols": ["FLOWER$string$3"]},
    {"name": "FLOWER$string$4", "symbols": [{"literal":" "}, {"literal":"l"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FLOWER", "symbols": ["FLOWER$string$4"]},
    {"name": "FLOWER$string$5", "symbols": [{"literal":" "}, {"literal":"f"}, {"literal":"l"}, {"literal":"o"}, {"literal":"w"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FLOWER", "symbols": ["FLOWER$string$5"]},
    {"name": "FLOWER$string$6", "symbols": [{"literal":" "}, {"literal":"m"}, {"literal":"a"}, {"literal":"p"}, {"literal":"l"}, {"literal":"e"}, {"literal":" "}, {"literal":"l"}, {"literal":"e"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FLOWER", "symbols": ["FLOWER$string$6"]},
    {"name": "FLOWER$string$7", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"b"}, {"literal":"o"}, {"literal":"u"}, {"literal":"g"}, {"literal":"h"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FLOWER", "symbols": ["FLOWER$string$7", "TREE"]},
    {"name": "FLOWER$string$8", "symbols": [{"literal":" "}, {"literal":"f"}, {"literal":"l"}, {"literal":"o"}, {"literal":"w"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}, {"literal":" "}, {"literal":"f"}, {"literal":"r"}, {"literal":"o"}, {"literal":"m"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FLOWER", "symbols": ["FLOWER$string$8", "TREE"]},
    {"name": "FLOWER$string$9", "symbols": [{"literal":" "}, {"literal":"l"}, {"literal":"e"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}, {"literal":"s"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FLOWER", "symbols": ["TREE", "FLOWER$string$9"]},
    {"name": "TREE$string$1", "symbols": [{"literal":" "}, {"literal":"o"}, {"literal":"a"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TREE", "symbols": ["TREE$string$1"]},
    {"name": "TREE$string$2", "symbols": [{"literal":" "}, {"literal":"b"}, {"literal":"e"}, {"literal":"e"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TREE", "symbols": ["TREE$string$2"]},
    {"name": "TREE$string$3", "symbols": [{"literal":" "}, {"literal":"p"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TREE", "symbols": ["TREE$string$3"]},
    {"name": "TREE$string$4", "symbols": [{"literal":" "}, {"literal":"m"}, {"literal":"a"}, {"literal":"p"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TREE", "symbols": ["TREE$string$4"]},
    {"name": "TREE$string$5", "symbols": [{"literal":" "}, {"literal":"g"}, {"literal":"i"}, {"literal":"n"}, {"literal":"k"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TREE", "symbols": ["TREE$string$5"]},
    {"name": "TREE$string$6", "symbols": [{"literal":" "}, {"literal":"p"}, {"literal":"l"}, {"literal":"u"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TREE", "symbols": ["TREE$string$6"]},
    {"name": "TREE$string$7", "symbols": [{"literal":" "}, {"literal":"c"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TREE", "symbols": ["TREE$string$7"]}
]
  , ParserStart: "main"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
